
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sevkikaragol
 */
public class AnaEkran extends javax.swing.JFrame {
    Sqlite baglanti=new Sqlite();
    int id;
    
    /**
     * Creates new form AnaEkran
     */
    public AnaEkran() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kullanici_eposta = new javax.swing.JTextField();
        sifre = new javax.swing.JPasswordField();
        aEposta = new javax.swing.JLabel();
        aSifre = new javax.swing.JLabel();
        oturumAc = new javax.swing.JLabel();
        kayitOl = new javax.swing.JLabel();
        carpi = new javax.swing.JLabel();
        eksi = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);
        jPanel1.add(kullanici_eposta);
        kullanici_eposta.setBounds(380, 390, 260, 30);
        jPanel1.add(sifre);
        sifre.setBounds(380, 460, 260, 30);

        aEposta.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        aEposta.setForeground(new java.awt.Color(255, 255, 255));
        aEposta.setText("E-posta");
        jPanel1.add(aEposta);
        aEposta.setBounds(470, 360, 120, 30);

        aSifre.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        aSifre.setForeground(new java.awt.Color(255, 255, 255));
        aSifre.setText("Şifre");
        jPanel1.add(aSifre);
        aSifre.setBounds(470, 430, 120, 30);

        oturumAc.setBackground(new java.awt.Color(255, 0, 0));
        oturumAc.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        oturumAc.setForeground(new java.awt.Color(255, 255, 255));
        oturumAc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oturumAc.setText("Oturum Aç");
        oturumAc.setOpaque(true);
        oturumAc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oturumAcMouseClicked(evt);
            }
        });
        jPanel1.add(oturumAc);
        oturumAc.setBounds(410, 530, 190, 40);

        kayitOl.setBackground(new java.awt.Color(255, 0, 0));
        kayitOl.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        kayitOl.setForeground(new java.awt.Color(255, 255, 255));
        kayitOl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kayitOl.setText("Kayıt Ol");
        kayitOl.setMaximumSize(new java.awt.Dimension(130, 30));
        kayitOl.setMinimumSize(new java.awt.Dimension(130, 30));
        kayitOl.setOpaque(true);
        kayitOl.setPreferredSize(new java.awt.Dimension(130, 30));
        kayitOl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kayitOlMouseClicked(evt);
            }
        });
        jPanel1.add(kayitOl);
        kayitOl.setBounds(410, 600, 190, 40);

        carpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpı.png"))); // NOI18N
        carpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carpiMouseClicked(evt);
            }
        });
        jPanel1.add(carpi);
        carpi.setBounds(970, 20, 35, 35);

        eksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eksi.png"))); // NOI18N
        eksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eksiMouseClicked(evt);
            }
        });
        jPanel1.add(eksi);
        eksi.setBounds(920, 20, 35, 35);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.png"))); // NOI18N
        jPanel1.add(background);
        background.setBounds(0, 0, 1020, 768);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 770);

        setSize(new java.awt.Dimension(1019, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kayitOlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kayitOlMouseClicked
     baglanti.dbKapat();
     this.dispose();
     KayitOl nesne=new KayitOl();
     nesne.setVisible(true);
     
    }//GEN-LAST:event_kayitOlMouseClicked

    private void oturumAcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oturumAcMouseClicked
        int kontrol1= baglanti.oturumAc(kullanici_eposta.getText(),
                new String(sifre.getPassword()));
        
        if(kontrol1==1){
            
       id=baglanti.userIdBul(kullanici_eposta.getText());
       
        baglanti.dbKapat();
       IcerikSayfasi nesne=new IcerikSayfasi(id);
       this.setVisible(false);
       nesne.setVisible(true);
        }
       else{
            int kontrol2=baglanti.kontrolEt2(kullanici_eposta.getText());
            if(kontrol2==0){
                 JOptionPane uyari1=new JOptionPane();
                 uyari1.showMessageDialog(rootPane,"Girdiğiniz şifre "
                         + "hatalidir.");
            }else{
                JOptionPane uyari2=new JOptionPane();
                 uyari2.showMessageDialog(rootPane,"Girdiğiniz bilgiler sisteme"
                  + " kayitli degildir. Kayit ekranina yonlendiriliyorsunuz. ");
                     this.dispose();
                      KayitOl nesne=new KayitOl();
                      nesne.setVisible(true);
                     
            }
            
            
        }
        
        
    }//GEN-LAST:event_oturumAcMouseClicked

    private void eksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eksiMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_eksiMouseClicked

    private void carpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carpiMouseClicked
       System.exit(0);
    }//GEN-LAST:event_carpiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaEkran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaEkran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aEposta;
    private javax.swing.JLabel aSifre;
    private javax.swing.JLabel background;
    private javax.swing.JLabel carpi;
    private javax.swing.JLabel eksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kayitOl;
    private javax.swing.JTextField kullanici_eposta;
    private javax.swing.JLabel oturumAc;
    private javax.swing.JPasswordField sifre;
    // End of variables declaration//GEN-END:variables
}
