
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sevkikaragol
 */
public class FilmOnerileri extends javax.swing.JFrame {
    Sqlite baglanti=new Sqlite();
   
    /**
     * Creates new form FilmOnerileri
     */
        String tur1;     
        String tur2;
        String tur3;
      ArrayList<Integer> onerilenlerId;  
      ArrayList<String> onerilenlerAd;
    public FilmOnerileri(String secim1,String secim2,String secim3 ) {
        tur1=secim1;
        tur2=secim2;
        tur3=secim3;
        onerilenlerId= baglanti.onerilenEkle(tur1, tur2, tur3);
        onerilenlerAd=baglanti.programAdlari(onerilenlerId);
        initComponents();
        ekle();
        
        
    }
     public void ekle(){
         
         DefaultTableModel tablo=(DefaultTableModel)oneriler.getModel();
         Object[]onerilenler1={onerilenlerAd.get(0),tur1};
         tablo.addRow(onerilenler1);
         
         Object[]onerilenler2={onerilenlerAd.get(1),tur1};
         tablo.addRow(onerilenler2);
         
         Object[]onerilenler3={onerilenlerAd.get(2),tur2};
         tablo.addRow(onerilenler3);
         
         Object[]onerilenler4={onerilenlerAd.get(3),tur2};
         tablo.addRow(onerilenler4);
         
         Object[]onerilenler5={onerilenlerAd.get(4),tur3};
         tablo.addRow(onerilenler5);
         
         Object[]onerilenler6={onerilenlerAd.get(5),tur3};
         tablo.addRow(onerilenler6);
    
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        giriseDon = new javax.swing.JLabel();
        carpi = new javax.swing.JLabel();
        eksi = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        oneriler = new javax.swing.JTable();
        iste = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        giriseDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/geri_butonu_v2.png"))); // NOI18N
        giriseDon.setText("jLabel1");
        giriseDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giriseDonMouseClicked(evt);
            }
        });
        jPanel1.add(giriseDon);
        giriseDon.setBounds(370, 620, 240, 80);

        carpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpı.png"))); // NOI18N
        carpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carpiMouseClicked(evt);
            }
        });
        jPanel1.add(carpi);
        carpi.setBounds(970, 20, 35, 35);

        eksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eksi.png"))); // NOI18N
        eksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eksiMouseClicked(evt);
            }
        });
        jPanel1.add(eksi);
        eksi.setBounds(920, 20, 35, 35);

        oneriler.setBackground(new java.awt.Color(0, 0, 0));
        oneriler.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        oneriler.setForeground(new java.awt.Color(255, 0, 0));
        oneriler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        oneriler.setInheritsPopupMenu(true);
        oneriler.setRowHeight(40);
        jScrollPane1.setViewportView(oneriler);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 270, 960, 260);

        iste.setBackground(new java.awt.Color(0, 0, 0));
        iste.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        iste.setForeground(new java.awt.Color(255, 0, 0));
        iste.setText("İşte senin için öneriler!");
        jPanel1.add(iste);
        iste.setBounds(400, 230, 340, 50);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Önerilen içerikler ve daha fazlası için şimdi giriş yap!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 590, 570, 30);

        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filmonerisi_background.png"))); // NOI18N
        arkaplan.setText("jLabel1");
        jPanel1.add(arkaplan);
        arkaplan.setBounds(0, 0, 1030, 768);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 770);

        setSize(new java.awt.Dimension(1020, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void giriseDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giriseDonMouseClicked
        baglanti.dbKapat();
        AnaEkran nesne=new AnaEkran();
        this.dispose();
        nesne.setVisible(true);
        
    }//GEN-LAST:event_giriseDonMouseClicked

    private void carpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carpiMouseClicked
        System.exit(0);
    }//GEN-LAST:event_carpiMouseClicked

    private void eksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eksiMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_eksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilmOnerileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilmOnerileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilmOnerileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilmOnerileri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new FilmOnerileri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel arkaplan;
    private javax.swing.JLabel carpi;
    private javax.swing.JLabel eksi;
    private javax.swing.JLabel giriseDon;
    private javax.swing.JLabel iste;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable oneriler;
    // End of variables declaration//GEN-END:variables
}
