
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
//import sun.audio.AudioPlayer;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sevkikaragol
 */
public class IcerikSayfasi extends javax.swing.JFrame {
     Sqlite baglanti=new Sqlite();
     ArrayList<String> programAdlari; 
     int user_id;
     String aranan;
     int secilenBolum;
     int kacBolum; // program kac bolum?
     int verilenPuanTut;
     long endTime;
     long startTime;
     long estimatedTime;
     int gecenZaman;
     int program_id;
      ResultSet rs2;
     int eklenecekZaman = 0;
     boolean bPlay=false;
    int icerikBolums;
    /**
     * Creates new form IcerikSayfasi
     */
    
    public IcerikSayfasi(int userId) {
        
        user_id=userId;
        initComponents();
        izleme.setVisible(false);
        oynat.setVisible(false);
        durdur.setVisible(false);
        bolumSecin.setVisible(false);
        bolumSecici.setVisible(false);
        verilenPuan.setVisible(false);
        puanVerLabel.setVisible(false);
        izleniyor.setVisible(false);
    }
   
    void tabloDoldur(){
        
        
         DefaultTableModel tablo=(DefaultTableModel)icerik.getModel();
        for (int i = 0; i < programAdlari.size(); i++) {
          Object[]aranan={programAdlari.get(i)};
        tablo.addRow(aranan);
            
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        arama = new javax.swing.JTextField();
        carpi = new javax.swing.JLabel();
        eksi = new javax.swing.JLabel();
        verilenPuan = new javax.swing.JTextField();
        izleniyor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        icerik = new javax.swing.JTable();
        izleme = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        izlemeBack = new javax.swing.JLabel();
        oynat = new javax.swing.JLabel();
        durdur = new javax.swing.JLabel();
        bolumSecin = new javax.swing.JLabel();
        bolumSecici = new javax.swing.JPanel();
        bolum1 = new javax.swing.JButton();
        bolum2 = new javax.swing.JButton();
        bolum3 = new javax.swing.JButton();
        bolum4 = new javax.swing.JButton();
        bolum5 = new javax.swing.JButton();
        puanVerLabel = new javax.swing.JLabel();
        arkaplan = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Netflix");
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        arama.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                aramaKeyReleased(evt);
            }
        });
        jPanel1.add(arama);
        arama.setBounds(210, 60, 510, 30);

        carpi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/carpı.png"))); // NOI18N
        carpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carpiMouseClicked(evt);
            }
        });
        jPanel1.add(carpi);
        carpi.setBounds(970, 20, 35, 35);

        eksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/eksi.png"))); // NOI18N
        eksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eksiMouseClicked(evt);
            }
        });
        jPanel1.add(eksi);
        eksi.setBounds(920, 20, 35, 35);

        verilenPuan.setText("0");
        jPanel1.add(verilenPuan);
        verilenPuan.setBounds(380, 430, 100, 30);

        izleniyor.setFont(new java.awt.Font("Candara", 1, 48)); // NOI18N
        izleniyor.setForeground(new java.awt.Color(255, 255, 255));
        izleniyor.setText("İçerik izleniyor...");
        jPanel1.add(izleniyor);
        izleniyor.setBounds(350, 220, 370, 60);

        icerik.setAutoCreateRowSorter(true);
        icerik.setBackground(new java.awt.Color(0, 0, 0));
        icerik.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        icerik.setForeground(new java.awt.Color(255, 255, 255));
        icerik.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        icerik.setRowHeight(24);
        icerik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icerikMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(icerik);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(210, 110, 510, 290);

        izleme.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        izleme.add(jLabel1);
        jLabel1.setBounds(20, 40, 240, 40);

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        izleme.add(jLabel2);
        jLabel2.setBounds(20, 100, 250, 20);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        izleme.add(jLabel3);
        jLabel3.setBounds(20, 160, 230, 20);

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        izleme.add(jLabel4);
        jLabel4.setBounds(270, 40, 220, 20);

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        izleme.add(jLabel5);
        jLabel5.setBounds(270, 100, 220, 20);

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        izleme.add(jLabel6);
        jLabel6.setBounds(270, 150, 220, 30);

        jLabel7.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        izleme.add(jLabel7);
        jLabel7.setBounds(280, 180, 200, 30);

        izlemeBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/filmonerisi_background.png"))); // NOI18N
        izleme.add(izlemeBack);
        izlemeBack.setBounds(0, 0, 500, 260);

        jPanel1.add(izleme);
        izleme.setBounds(80, 480, 500, 260);

        oynat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/oynat.png"))); // NOI18N
        oynat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                oynatMouseClicked(evt);
            }
        });
        jPanel1.add(oynat);
        oynat.setBounds(640, 530, 270, 90);

        durdur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/durdur.png"))); // NOI18N
        durdur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                durdurMouseClicked(evt);
            }
        });
        jPanel1.add(durdur);
        durdur.setBounds(640, 640, 250, 90);

        bolumSecin.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        bolumSecin.setForeground(new java.awt.Color(255, 255, 255));
        bolumSecin.setText("Bölüm Seçiniz:");
        jPanel1.add(bolumSecin);
        bolumSecin.setBounds(690, 450, 170, 30);

        bolumSecici.setLayout(null);

        bolum1.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bolum1.setText("1");
        bolum1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolum1ActionPerformed(evt);
            }
        });
        bolumSecici.add(bolum1);
        bolum1.setBounds(0, 0, 50, 40);

        bolum2.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bolum2.setText("2");
        bolum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolum2ActionPerformed(evt);
            }
        });
        bolumSecici.add(bolum2);
        bolum2.setBounds(50, 0, 50, 40);

        bolum3.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bolum3.setText("3");
        bolum3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolum3ActionPerformed(evt);
            }
        });
        bolumSecici.add(bolum3);
        bolum3.setBounds(100, 0, 50, 40);

        bolum4.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bolum4.setText("4");
        bolum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolum4ActionPerformed(evt);
            }
        });
        bolumSecici.add(bolum4);
        bolum4.setBounds(150, 0, 50, 40);

        bolum5.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        bolum5.setText("5");
        bolum5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolum5ActionPerformed(evt);
            }
        });
        bolumSecici.add(bolum5);
        bolum5.setBounds(200, 0, 50, 40);

        jPanel1.add(bolumSecici);
        bolumSecici.setBounds(630, 480, 250, 40);

        puanVerLabel.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        puanVerLabel.setForeground(new java.awt.Color(255, 255, 255));
        puanVerLabel.setText("*1-10 arası puan veriniz. ->");
        jPanel1.add(puanVerLabel);
        puanVerLabel.setBounds(170, 430, 220, 30);

        arkaplan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icerik_background.png"))); // NOI18N
        arkaplan.setText("jLabel1");
        jPanel1.add(arkaplan);
        arkaplan.setBounds(0, 0, 1020, 770);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 770);

        setSize(new java.awt.Dimension(1020, 768));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void carpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carpiMouseClicked
       if(bPlay==true){
           JOptionPane mesaj1=new JOptionPane();
           mesaj1.showMessageDialog(rootPane,"Lutfen çıkmadan once izlenen programı DURDURUNUZ!");
       }else
        System.exit(0);
    }//GEN-LAST:event_carpiMouseClicked

    private void eksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eksiMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_eksiMouseClicked

    private void aramaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_aramaKeyReleased
        DefaultTableModel tablo=(DefaultTableModel)icerik.getModel();
        tablo.getDataVector().removeAllElements();
        icerik.repaint();
        
        aranan=arama.getText();
        programAdlari=baglanti.programAdiBul(aranan);
        tabloDoldur();
    }//GEN-LAST:event_aramaKeyReleased

    private void icerikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icerikMouseClicked
        izleme.setVisible(true);
        //oynat.setVisible(true);
       bolumSecici.setVisible(false);
       oynat.setVisible(false);
       bolumSecin.setVisible(false);
       durdur.setVisible(false);
       
       secilenBolum=0;
        
        
        String programAdi;
        
        int secilisatir=icerik.getSelectedRow();
        programAdi=icerik.getValueAt(secilisatir,0).toString();
        System.out.println(programAdi);
        ResultSet rs=baglanti.programBilgileri(programAdi);
        
         try {
             icerikBolums = rs.getInt("PROGRAM_BOLUM");
         } catch (SQLException ex) {
             Logger.getLogger(IcerikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
         }
        
        jLabel1.setText(programAdi);
         try {
             
             if(icerikBolums!=1){
             jLabel2.setVisible(true); //eklendi
             jLabel2.setText("Bölüm Sayısı: "+String.valueOf(rs.getInt("PROGRAM_BOLUM")));
             }
             if(icerikBolums==1) jLabel2.setVisible(false); //eklendi
             
             jLabel3.setText("Program Uzunlugu:"
                       +String.valueOf(rs.getInt("PROGRAM_UZUNLUK"))+ " dk");
             program_id= rs.getInt("ID");
             System.out.println(program_id);
             
            
         
         } catch (SQLException ex) {
             System.out.println("basarisiz jlabel 2-3");
         }
            
         //kullanici program tablosundan alınan bilgiler icin
            // rs2 tepeye tasindi
            System.out.println(user_id);
            rs2 = baglanti.izlemeBilgi(user_id,program_id);
            
            if(rs2==null){
                jLabel4.setVisible(true);  //eklendi 
                jLabel4.setText("Henuz bu iceriği izlemediniz.");
                jLabel5.setVisible(false);
                jLabel6.setVisible(false);
                jLabel7.setVisible(false);
            }else {
                if(icerikBolums==1) {
                    jLabel4.setVisible(false);
                    jLabel2.setVisible(false);
                
                }
                
               
                if(icerikBolums==5){
                    jLabel4.setVisible(true);
                    jLabel2.setVisible(true);
                }
            try {
                jLabel5.setVisible(true);
                jLabel6.setVisible(true);
                jLabel7.setVisible(true);
                
                if(icerikBolums!=1)
                jLabel4.setText(String.valueOf(rs2.getInt("EPISODE")) +".bölümde kalmıştınız.");
                
                jLabel5.setText(String.valueOf(rs2.getInt("MONITORING_TIME"))+". dakikada kalmıştınız.");
                jLabel6.setText("Son izlediğiniz tarih:");
                jLabel7.setText(rs2.getString("MONITORING_DATE"));
            } catch (SQLException ex) {
                Logger.getLogger(IcerikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
            }
                
            
            
            }
         try {
             kacBolum=rs.getInt("PROGRAM_BOLUM");
             
             if(kacBolum!=1){
                 
                 bolumSecin.setVisible(true);
                 bolumSecici.setVisible(true);
                 
                 
                
                 
             }else{
                 oynat.setVisible(true);
             }
             
         } catch (SQLException ex) {
             Logger.getLogger(IcerikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
         }
         
            if(secilenBolum!=0){
                     bolumSecin.setVisible(false);
                     bolumSecici.setVisible(false);
                     oynat.setVisible(true);
                     
                 }
        
         
         
        
        
       
    }//GEN-LAST:event_icerikMouseClicked

    private void bolum1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolum1ActionPerformed
        secilenBolum=1;
        oynat.setVisible(true);
        bolumSecici.setVisible(false);
        bolumSecin.setVisible(false);
    }//GEN-LAST:event_bolum1ActionPerformed

    private void bolum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolum2ActionPerformed
        secilenBolum=2;
        oynat.setVisible(true);
        bolumSecici.setVisible(false);
        bolumSecin.setVisible(false);
    }//GEN-LAST:event_bolum2ActionPerformed

    private void bolum3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolum3ActionPerformed
         secilenBolum=3;
        oynat.setVisible(true);
        bolumSecici.setVisible(false);
        bolumSecin.setVisible(false);
    }//GEN-LAST:event_bolum3ActionPerformed

    private void bolum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolum4ActionPerformed
         secilenBolum=4;
        oynat.setVisible(true);
        bolumSecici.setVisible(false);
        bolumSecin.setVisible(false);
    }//GEN-LAST:event_bolum4ActionPerformed

    private void bolum5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolum5ActionPerformed
        secilenBolum=5;
        oynat.setVisible(true);
        bolumSecici.setVisible(false);
        bolumSecin.setVisible(false);
    }//GEN-LAST:event_bolum5ActionPerformed

    
    
    private void oynatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_oynatMouseClicked
        bPlay=true;
        jScrollPane1.setVisible(false);
        izleniyor.setVisible(true);
        arama.setVisible(false);
        verilenPuan.setVisible(true);
        puanVerLabel.setVisible(true);
        durdur.setVisible(true);
        
        int kalinanBolum;
        if(rs2!=null&&kacBolum==1){
            //System.out.println("ife girdi");
         try {
         eklenecekZaman = rs2.getInt("MONITORING_TIME");
         
         
         
         } catch (SQLException ex) {
             System.out.println("Eklenecek zaman bulunamadi.");
         }
        }if(rs2==null&&kacBolum==1){
           eklenecekZaman=0;
        }
        
        
        
        if(rs2!=null && kacBolum==5){
            try {
                kalinanBolum=rs2.getInt("EPISODE");
                if(kalinanBolum==secilenBolum){
                eklenecekZaman = rs2.getInt("MONITORING_TIME");
               
                
            }
                else{
                    eklenecekZaman=0;
                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(IcerikSayfasi.class.getName()).log(Level.SEVERE, null, ex);
            }

       
        
        System.out.println("Eklenecek zaman "+eklenecekZaman);
        
        }if(rs2==null&&kacBolum==5){
            eklenecekZaman=0;
        }
        
        startTime=System.nanoTime();
    }//GEN-LAST:event_oynatMouseClicked
    
    
    private void durdurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_durdurMouseClicked
       bPlay=false;
       verilenPuanTut=Integer.parseInt(verilenPuan.getText());
       
        if(verilenPuanTut==0){
            JOptionPane uyari=new JOptionPane();
            uyari.showMessageDialog(rootPane,"Durdurmak için puan vermeniz"
                    + " gerekmektedir!");
        }else if(verilenPuanTut>10||0>verilenPuanTut){
            JOptionPane uyari2=new JOptionPane();
            uyari2.showMessageDialog(rootPane,"Geçerli bir puan vermeniz"
                    + " gerekmektedir!");
        }
        else{
            endTime = System.nanoTime();
            estimatedTime = endTime - startTime;
            gecenZaman = (int)(estimatedTime/1000000000)+eklenecekZaman;
           
            
            
            int tercih=0;
            ResultSet rs3=baglanti.izlemeBilgi(user_id, program_id);
            
            if(rs3==null) tercih=1;
            
            if(rs3!=null) tercih=2;
            
            if(kacBolum==1) secilenBolum=1;
            
            baglanti.programKullaniciGuncelle(tercih,user_id,program_id
                    ,gecenZaman,secilenBolum,verilenPuanTut);
            
           
            oynat.setVisible(false);
            verilenPuan.setText("0");
            verilenPuan.setVisible(false);
            puanVerLabel.setVisible(false);
            durdur.setVisible(false);
            izleme.setVisible(false);
            izleniyor.setVisible(false);
            jScrollPane1.setVisible(true);
            arama.setVisible(true);
            
        }
        
                
    }//GEN-LAST:event_durdurMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IcerikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IcerikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IcerikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IcerikSayfasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new IcerikSayfasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField arama;
    private javax.swing.JLabel arkaplan;
    private javax.swing.JButton bolum1;
    private javax.swing.JButton bolum2;
    private javax.swing.JButton bolum3;
    private javax.swing.JButton bolum4;
    private javax.swing.JButton bolum5;
    private javax.swing.JPanel bolumSecici;
    private javax.swing.JLabel bolumSecin;
    private javax.swing.JLabel carpi;
    private javax.swing.JLabel durdur;
    private javax.swing.JLabel eksi;
    private javax.swing.JTable icerik;
    private javax.swing.JPanel izleme;
    private javax.swing.JLabel izlemeBack;
    private javax.swing.JLabel izleniyor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel oynat;
    private javax.swing.JLabel puanVerLabel;
    private javax.swing.JTextField verilenPuan;
    // End of variables declaration//GEN-END:variables
}
